# BUILDER da aplicação em go
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o webhook-watcher main.go


# APLICAÇÃO FINAL
FROM alpine:3.23

WORKDIR /app

COPY --from=builder /app/webhook-watcher .

# para o sqlite
VOLUME /app/data

EXPOSE 3000

CMD ["./webhook-watcher"]