# BUILDER da aplicação em go
FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o webhook-watcher .

# APLICAÇÃO FINAL
FROM alpine:3.23

WORKDIR /app

COPY --from=builder /app/webhook-watcher .

CMD ["./webhook-watcher"]